### ISSUE TITLE
[3.0] Roadmap

### ISSUE THREAD

**Issue by franmomu** [nelmio/NelmioSecurityBundle#256]
This is a list of things I think it would be nice to have for `3.0`, feel free to suggest more:

- [x] [Add Static Analysis (we should do this by steps until reaching an acceptable level)](https://github.com/nelmio/NelmioSecurityBundle/pull/282)
  - [x] [Add strict rules](https://github.com/nelmio/NelmioSecurityBundle/pull/277)
  - [x] [Add deprecations rules](https://github.com/nelmio/NelmioSecurityBundle/pull/285)
- [x] Add type declarations
- [x] [Use strict types](https://github.com/nelmio/NelmioSecurityBundle/pull/261)
- [x] Update documentation
- [x] Revisit visibility of things ([final classes](https://github.com/nelmio/NelmioSecurityBundle/pull/290), make private properties, private constants, use internal annotation, etc)
- [x] [Remove deprecations](https://github.com/nelmio/NelmioSecurityBundle/pull/285)
- [x] [Avoid triggering deprecations (with `SYMFONY_DEPRECATIONS_HELPER`)](https://github.com/nelmio/NelmioSecurityBundle/pull/273)
- [x] [Add functional tests (for the controller at least)](https://github.com/nelmio/NelmioSecurityBundle/pull/271)
- [x] [Remove `DoctrineCacheUAFamilyParser` in favor of `PsrCacheUAFamilyParser`](https://github.com/nelmio/NelmioSecurityBundle/pull/263)
- [x] [Make Twig extension lazy loaded](https://github.com/nelmio/NelmioSecurityBundle/pull/283)
- [x] [Replace the term whitelist with allowlist or similar](https://github.com/nelmio/NelmioSecurityBundle/pull/291)

Other things:
- [x] [Move YAML configuration to PHP](https://github.com/nelmio/NelmioSecurityBundle/pull/286)
- [x] [Check with composer normalize](https://github.com/nelmio/NelmioSecurityBundle/pull/284)

**Comment by franmomu** [comment]
https://github.com/nelmio/NelmioSecurityBundle/releases/tag/v3.0.0 has been released
